# -*- coding: utf-8 -*-
"""masking.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P2vpSHxAsnRxz2iP6F4-j2vy-gJrroNM
"""

import copy
import numpy as np
import cv2
import random

def horizontal_mask(image, size = 30, num_masks=1):
    cloned = copy.deepcopy(image)
    len_spectro = cloned.shape[1]

    for i in range(0,num_masks):
        s = random.randrange(10,size)
        s_zero = random.randrange(10,len_spectro-s)

        # avoids randrange error if values are equal and range is empty
        if (s_zero==s_zero+s):
            return cloned
        mask_end = random.randrange(s_zero, s_zero+s)
        cloned[:,s_zero:mask_end]=0
    return cloned

def vertical_mask(image, size = 30, num_masks=1):
    cloned = copy.deepcopy(image)
    len_spectro = cloned.shape[1]

    for i in range(0,num_masks):
        s = random.randrange(10,size)
        s_zero = random.randrange(10,len_spectro-s)

        # avoids randrange error if values are equal and range is empty
        if (s_zero==s_zero+s):
            return cloned
        mask_end = random.randrange(s_zero, s_zero+s)
        cloned[s_zero:mask_end]=0
    return cloned