# -*- coding: utf-8 -*-
"""ensenble.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CAhHrMA3Pg403szXpku4vABuSNnooMyA
"""

import csv
csvfile1 = open('../submit_cancer_ysf_16.csv', newline='')
csvfile2 = open('../submit_cancer_ysf_17.csv', newline='')
csvfile_out = open('../submit_cancer_ysf_17_16_ensembeled.csv', 'w', newline='')
writer = csv.writer(csvfile_out, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
reader_16 = csv.reader(csvfile1, delimiter=',', quotechar='|')
reader_17 = csv.reader(csvfile2, delimiter=',', quotechar='|')
score = 0.0
for i,(row16,row17) in enumerate(zip(reader_16,reader_17)):
   if i == 0:
      writer.writerow([row16[0],row16[1]])
      continue
   if float(row17[1])>0.8:
      score = row17[1]
   if float(row17[1]) < 0.6:
      score = row16[1]
   writer.writerow([row16[0],score])
   print(row16[0],score)