# -*- coding: utf-8 -*-
"""mean.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CAhHrMA3Pg403szXpku4vABuSNnooMyA
"""

import torch
import torch.nn as nn
import numpy as np
import os
import sys
sys.path.append('../')
from DATALOADER.dataloader_cancer_ysf import train_oralData


mean = 0.
std = 0.
nb_samples = 0.

for i, data in enumerate(train_oralData):
    print(i)
    images = data['image']
    batch_samples = images.size(0)
    images = images.view(batch_samples, images.size(1), -1)
    mean += images.mean(2).sum(0)
    std += images.std(2).sum(0)
    nb_samples += batch_samples

print(mean/nb_samples)
print(std/nb_samples)