name: CI

runs:
  using: 'composite'
    steps:
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check --line-length 119"
      - uses: isort/isort-action@master
        with:
          configuration: "--profile black --check-only --diff --line-length 119"
